In [1]:
import tensorflow as tf 

In [2]:
tf.version.VERSION

'2.13.0'

In [3]:
# check if your are running on GPU
tf.config.list_logical_devices() 

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [5]:
#create constant
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

In [6]:
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [8]:
#Create dummy data
X = tf.random.uniform(shape=[100, 2])
y = tf.random.uniform(shape=[100, 1])

In [9]:
 X.shape, y.shape

(TensorShape([100, 2]), TensorShape([100, 1]))

In [11]:
# Create some basic datatypes
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [13]:
 x = tf.ones((4, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [14]:
 x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.2784052 0.317986 ]
 [0.7388768 0.9594244]], shape=(2, 2), dtype=float32)


In [15]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [16]:
 x = tf.constant([5])
y = tf.constant([6])
ztf = tf.multiply(x, y)
z = x * y
print(ztf)
print(z)

tf.Tensor([30], shape=(1,), dtype=int32)
tf.Tensor([30], shape=(1,), dtype=int32)


In [18]:
#Keras framwork
#Import keras from TensorFlow
from tensorflow import keras
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [19]:
dir(tf.keras.layers)[:10] 

['AbstractRNNCell',
 'Activation',
 'ActivityRegularization',
 'Add',
 'AdditiveAttention',
 'AlphaDropout',
 'Attention',
 'Average',
 'AveragePooling1D',
 'AveragePooling2D']

In [21]:
#Load Keras datasets
from tensorflow.keras import datasets
from tensorflow.keras.datasets import mnist 

In [22]:
[x for x in dir(datasets) if x.find("__") == -1] 

['boston_housing',
 'cifar10',
 'cifar100',
 'fashion_mnist',
 'imdb',
 'mnist',
 'reuters']

In [23]:
(x_train, y_train), (x_test, y_test) = mnist.load_data() 

11490434/11490434 [==============================] - 2s 0us/step


In [24]:
#Loading and accessing TensorFlow Keras layers
from tensorflow import keras
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import layers

In [25]:
model = keras.Sequential(
    [
        keras.Input(shape=(28 * 28)),
        layers.Dense(512, activation="relu"),
        layers.Dense(256, activation="relu"),
        layers.Dense(10),
    ]
)

In [26]:
dir(layers)[:10]

['AbstractRNNCell',
 'Activation',
 'ActivityRegularization',
 'Add',
 'AdditiveAttention',
 'AlphaDropout',
 'Attention',
 'Average',
 'AveragePooling1D',
 'AveragePooling2D']

In [27]:
model = keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation="relu"))
model.add(layers.Dense(256, activation="relu", name="my_layer"))
model.add(layers.Dense(10))

In [28]:
 # style 3: functional API
inputs = keras.Input(shape=(784))
x = layers.Dense(512, activation="relu", name="first_layer")(inputs)
x = layers.Dense(256, activation="relu", name="second_layer")(x)
outputs = layers.Dense(10, activation="softmax")(x)
model = keras.Model(inputs=inputs, outputs=outputs)