In [2]:
import tensorflow as tf 

In [30]:
X = tf.random.uniform((100, 5))
y = (X + 5) * 0.3

In [31]:
type(X), type(y) 

(tensorflow.python.framework.ops.EagerTensor,
 tensorflow.python.framework.ops.EagerTensor)

In [32]:
X.shape, y.shape 

(TensorShape([100, 5]), TensorShape([100, 5]))

In [33]:
#Define a simple Neural Network
model =  tf.keras.Sequential([
    tf.keras.layers.Input(name="InputLayer", shape=[1]),
    tf.keras.layers.Dense(100, name="Layer1"),
    tf.keras.layers.Dense(1, name="outputLayer2"),
 ])

In [35]:
 model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Layer1 (Dense)              (None, 100)               200       
                                                                 
 outputLayer2 (Dense)        (None, 1)                 101       
                                                                 
Total params: 301 (1.18 KB)
Trainable params: 301 (1.18 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [36]:
 model.layers[0].weights[0].shape

TensorShape([1, 100])

In [28]:
#Train Neural Network
model.compile(loss="MSE", optimizer="adam") 

In [29]:
model.fit(X, y, epochs=100)

Epoch 1/100


ValueError: in user code:

    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\engine\training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\engine\training.py", line 1322, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\engine\training.py", line 1303, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\engine\training.py", line 1080, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\engine\input_spec.py", line 280, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'sequential_1' (type Sequential).
    
    Input 0 of layer "Layer1" is incompatible with the layer: expected axis -1 of input shape to have value 1, but received input with shape (None, 5)
    
    Call arguments received by layer 'sequential_1' (type Sequential):
      • inputs=tf.Tensor(shape=(None, 5), dtype=float32)
      • training=True
      • mask=None


In [22]:
model.weights

[<tf.Variable 'Layer1/kernel:0' shape=(1, 100) dtype=float32, numpy=
 array([[ 0.13413534,  0.12848163,  0.16495648,  0.17582634, -0.2307949 ,
         -0.1604501 , -0.18480168, -0.07393377,  0.07082254,  0.14547518,
          0.21597213, -0.15947658,  0.13497671,  0.06117809,  0.20022666,
          0.05247715, -0.22279786, -0.21283539, -0.21832857, -0.13086107,
          0.04326773,  0.10017994,  0.08745396, -0.03091882,  0.17507073,
          0.0391334 ,  0.22278833, -0.00686954, -0.09971446, -0.24328485,
         -0.17746824,  0.01758006, -0.13738772,  0.05448794, -0.03253564,
          0.13423184,  0.00423679,  0.03859359, -0.09419809,  0.14094204,
         -0.21017677,  0.10969913,  0.00644016,  0.10950035,  0.09951225,
         -0.00507624, -0.21757436,  0.11746636,  0.23489398,  0.18361652,
          0.10764122, -0.13108125, -0.14336643,  0.06363884,  0.02160621,
          0.08730245, -0.10794303,  0.08787194,  0.14923564, -0.11635454,
         -0.00514109,  0.18046531,  0.19321

In [23]:
l = model.layers[0]

In [24]:
l.weights 

[<tf.Variable 'Layer1/kernel:0' shape=(1, 100) dtype=float32, numpy=
 array([[ 0.13413534,  0.12848163,  0.16495648,  0.17582634, -0.2307949 ,
         -0.1604501 , -0.18480168, -0.07393377,  0.07082254,  0.14547518,
          0.21597213, -0.15947658,  0.13497671,  0.06117809,  0.20022666,
          0.05247715, -0.22279786, -0.21283539, -0.21832857, -0.13086107,
          0.04326773,  0.10017994,  0.08745396, -0.03091882,  0.17507073,
          0.0391334 ,  0.22278833, -0.00686954, -0.09971446, -0.24328485,
         -0.17746824,  0.01758006, -0.13738772,  0.05448794, -0.03253564,
          0.13423184,  0.00423679,  0.03859359, -0.09419809,  0.14094204,
         -0.21017677,  0.10969913,  0.00644016,  0.10950035,  0.09951225,
         -0.00507624, -0.21757436,  0.11746636,  0.23489398,  0.18361652,
          0.10764122, -0.13108125, -0.14336643,  0.06363884,  0.02160621,
          0.08730245, -0.10794303,  0.08787194,  0.14923564, -0.11635454,
         -0.00514109,  0.18046531,  0.19321

In [25]:
(20.0 * l.weights[0][0]) + (3.0 * l.weights[0][1]) + ( l.weights[1]) 

InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:CPU:0}} slice index 1 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

In [37]:
 model.predict([[20.0, 1.0]])

ValueError: in user code:

    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\engine\training.py", line 2341, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\engine\training.py", line 2327, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\engine\training.py", line 2315, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\engine\training.py", line 2283, in predict_step
        return self(x, training=False)
    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\Mariya\anaconda3\lib\site-packages\keras\src\engine\input_spec.py", line 280, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'sequential_1' (type Sequential).
    
    Input 0 of layer "Layer1" is incompatible with the layer: expected axis -1 of input shape to have value 1, but received input with shape (None, 2)
    
    Call arguments received by layer 'sequential_1' (type Sequential):
      • inputs=tf.Tensor(shape=(None, 2), dtype=float32)
      • training=False
      • mask=None


In [26]:
# Plot the model
tf.keras.utils.plot_model(model) 

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [ ]:
 model.predict([9])

In [31]:
array([[4.271774]], dtype=float32)

NameError: name 'array' is not defined